export const nigerianAirForceRanks = [
  "Marshal of the Nigerian Air Force",
  "Air Chief Marshal",
  "Air Marshal",
  "Air Vice Marshal",
  "Air Commodore",
  "Group Captain",
  "Wing Commander",
  "Squadron Leader",
  "Flight Lieutenant",
  "Flying Officer",
  "Pilot Officer",
  "Air Warrant Officer",
  "Master Warrant Officer",
  "Warrant Officer",
  "Flight Sergeant",
  "Sergeant",
  "Corporal",
  "Lance Corporal",
];
export const ordainedNumberOfPracticeQuestions = 20;
